# Get all parcels.

GET http://localhost:9080/fast-delivery/api/parcels/

###

# Get all warehouses.

GET http://localhost:9080/fast-delivery/api/warehouses/

###
# Get parcel

GET http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb

###
# Get non-existent parcel

GET http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd2-4b02-9941-27aab5b2ecdb

###

# Get parcel image

GET http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image

###

# Insert parcel image when exists

PUT http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="delikatne.png"

< src/main/resources/images/delikatne.png
--boundary--

###

# Delete parcel image

DELETE http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image

###

# Patch parcel image

PATCH http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="delikatne.png"

< src/main/resources/images/delikatne.png
--boundary--

###

# Patch parcel image nr. 2

PATCH http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="paczka5.png"

< src/main/resources/images/paczka5.png
--boundary--

###

# Patch non-existent parcel image 

PATCH http://localhost:9080/fast-delivery/api/parcels/1c013543-5bd1-4b02-9941-27aab5b2ecdb/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="paczka5.png"

< src/main/resources/images/paczka5.png
--boundary--

###

# Get non-existent parcel's image

GET http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd2-4b02-9941-27aab5b2ecdb/image

###

# Get user

GET http://localhost:9080/fast-delivery/api/clients/12f2776c-f823-4aab-8eb3-0e4fd5ae32f9

###

# Get nonexistent user

GET http://localhost:9080/fast-delivery/api/clients/12f2776c-f823-4aab-8eb3-0e4fd5ae32f8

###
# Get users

GET http://localhost:9080/fast-delivery/api/clients

###

# Insert parcel

PUT http://localhost:9080/fast-delivery/api/parcels/38cae1cc-049c-41fd-b129-d7edfcf7f1fa
Content-Type: application/json

{
  "weight": 20.3,
  "status": "IN_DELIVERY",
  "deliveryDate": "2024-12-03",
  "warehouse": "baf6561e-f028-49ff-8b59-de9132b4e3dd",
  "client": "12f2776c-f823-4aab-8eb3-0e4fd5ae32f9"
}

###
# Get parcel

GET http://localhost:9080/fast-delivery/api/parcels/38cae1cc-049c-41fd-b129-d7edfcf7f1fa

###

# Put warehouse

PUT http://localhost:9080/fast-delivery/api/warehouses/3bd328e1-cb1b-4bc1-a10d-d734791d65b9
Content-Type: application/json

{
  "name": "Lotnisko w Warszawie",
  "location": "Warszawa",
  "establishedDate": "1994-02-16",
  "parcels": []
}

###

# Get warehouse

GET http://localhost:9080/fast-delivery/api/warehouses/3bd328e1-cb1b-4bc1-a10d-d734791d65b9

###

# Pathc parcel

PATCH http://localhost:9080/fast-delivery/api/parcels/38cae1cc-049c-41fd-b129-d7edfcf7f1fa
Content-Type: application/json

{
  "status": "DELIVERED",
  "deliveryDate": "2024-12-01"
}

###

# Patch warehouse

PATCH http://localhost:9080/fast-delivery/api/warehouses/3bd328e1-cb1b-4bc1-a10d-d734791d65b9
Content-Type: application/json

{
  "name": "Lotnisko Chopina w Warszawie",
  "location": "Żwirki i Wigury 1, 02-143 Warszawa"
}

###

# Delete warehouse

DELETE http://localhost:9080/fast-delivery/api/warehouses/baf6561e-f028-49ff-8b59-de9132b4e3dd

###

# Get warehouse

GET http://localhost:9080/fast-delivery/api/warehouses/baf6561e-f028-49ff-8b59-de9132b4e3dd

###

