# Get all parcels.

GET http://localhost:9080/fast-delivery/api/parcels/

###

# Get all warehouses.

GET http://localhost:9080/fast-delivery/api/warehouses/

###

# Get parcel image

GET http://localhost:9080/fast-delivery/api/parcels/1c023543-5bd1-4b02-9941-27aab5b2ecdb/image

###

# Update parcel image

PATCH

